CREATE DATABASE LibraryDB;

USE LibraryDB;

-- TABLES

CREATE TABLE Author(
Id VARCHAR(100) NOT NULL ,
FirstName VARCHAR(100) NOT NULL,
LastName VARCHAR(100) NOT NULL,
DateOfBirth DATE NOT NULL ,
CreatedOn DATETIME DEFAULT CURRENT_TIMESTAMP,
ModifiedOn DATETIME
);
x
CREATE TABLE Genre(
Id VARCHAR(100)NOT NULL,
Name VARCHAR(100) NOT NULL,
Description TEXT,
ParentGenreId VARCHAR(100),
);

CREATE TABLE Book(
Id VARCHAR(100) NOT NULL,
Title VARCHAR(100) NOT NULL,
PublishedDate DATE,
PublisherId VARCHAR(100) NOT NULL,
TotalPages INT,
Rating DECIMAL(3,2)
);

CREATE TABLE Publisher(
Id VARCHAR(100) NOT NULL,
Name VARCHAR(100) NOT NULL
);

CREATE TABLE Books_Genres(
BookId VARCHAR(100) NOT NULL,
GenreId VARCHAR(100) NOT NULL
);

CREATE TABLE Books_Authors(
BookId VARCHAR(100) NOT NULL,
AuthorId VARCHAR(100) NOT NULL
);



--PRIMARY KEYS

ALTER TABLE Author
ADD PRIMARY KEY(Id);

ALTER TABLE Genre
ADD PRIMARY KEY(Id),
FOREIGN KEY (ParentGenreId) REFERENCES Genre(Id);

ALTER TABLE Book
ADD PRIMARY KEY(Id),
CONSTRAINT CHK_Rating CHECK (Rating >= 0 AND Rating <= 5);

ALTER TABLE Publisher
ADD PRIMARY KEY(Id);

ALTER TABLE Books_Genres
ADD PRIMARY KEY(BookId,GenreId);

ALTER TABLE Books_Authors
ADD PRIMARY KEY(BookId,AuthorId);


-- FOREIGN KEYS

ALTER TABLE Books_Authors
ADD CONSTRAINT FK_Books_Authors_Author
FOREIGN KEY (AuthorId) REFERENCES Author(Id);

ALTER TABLE Books_Authors
ADD CONSTRAINT FK_Books_Authors_Book
FOREIGN KEY (BookId) REFERENCES Book(Id);

ALTER TABLE Books_Genres
ADD CONSTRAINT FK_Books_Genres_Genre
FOREIGN KEY (GenreId) REFERENCES Genre(Id);

ALTER TABLE Books_Genres
ADD CONSTRAINT FK_Books_Genres_Book
FOREIGN KEY (BookId) REFERENCES Book(Id);

ALTER TABLE Book 
ADD CONSTRAINT FK_Book_Publisher
FOREIGN KEY(PublisherId) REFERENCES Publisher(Id);

